#!/bin/sh
### BEGIN INIT INFO
# Provides:          sunshade-control
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sunshade control.
# Description:       A node.js server controlling sunshade through GPIO pins.
### END INIT INFO
RUN_AS=pi
APPJS="/home/$RUN_AS/sunshade-control/server/app.js"
PORT=1080
. /home/pi/.nvm/nvm.sh
NVM_NODE_PATH=/home/pi/.nvm/versions/node/v10.15.3
NODE=$NVM_NODE_PATH/bin/node
FOREVER=$NVM_NODE_PATH/bin/forever

case "$1" in
  start)
    sudo -u $RUN_AS PORT=$PORT NODE_ENV="production" $NODE $FOREVER start -p /home/$RUN_AS/.forever $APPJS
    ;;
  stop)
    sudo -u $RUN_AS $NODE $FOREVER stop $APPJS
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0
